# Generated by Django 3.1.1 on 2020-09-26 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(validators=[django.core.validators.MaxValueValidator(36), django.core.validators.MinValueValidator(47)])),
                ('shoe_size', models.IntegerField(choices=[(0, 36), (1, 37), (2, 38), (3, 39), (4, 40), (5, 41), (6, 42), (7, 43), (8, 44), (9, 45), (10, 46), (11, 47)], default=0)),
            ],
        ),
    ]
